### ISSUE TITLE
zero-arg call to Python `super()` not working

### ISSUE THREAD

**Issue by marius311** [JuliaPy/PyCall.jl#409]
As the title says, the zero-arg version of `super()` doesn't work, 

```julia
julia> @pydef type Foo
           __str__(self) = pybuiltin(:super)()[:__str__]()
       end
PyObject <class 'Foo'>

julia> Foo()[:__str__]()
ERROR: PyError (ccall(@pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, arg, C_NULL)) <class 'RuntimeError'>
RuntimeError('super(): no arguments',)
  File "PyCall", line 1, in <lambda>

Stacktrace:
 [1] pyerr_check at /home/marius/.julia/v0.6/PyCall/src/exception.jl:56 [inlined]
 [2] pyerr_check at /home/marius/.julia/v0.6/PyCall/src/exception.jl:61 [inlined]
 [3] macro expansion at /home/marius/.julia/v0.6/PyCall/src/exception.jl:81 [inlined]
 [4] #_pycall#66(::Array{Any,1}, ::Function, ::PyCall.PyObject) at /home/marius/.julia/v0.6/PyCall/src/PyCall.jl:620
 [5] #pycall#70(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::Type{PyCall.PyAny}) at /home/marius/.julia/v0.6/PyCall/src/PyCall.jl:642
 [6] #call#71 at /home/marius/.julia/v0.6/PyCall/src/PyCall.jl:645 [inlined]
 [7] (::PyCall.PyObject)() at /home/marius/.julia/v0.6/PyCall/src/PyCall.jl:645
```

although the manual version is fine,

```julia
julia> @pydef type Bar
           __str__(self) = pybuiltin(:super)(Bar,self)[:__str__]()
       end
PyObject <class 'Bar'>

julia> Bar()[:__str__]()
"<Bar object at 0x7f484b228b70>"
```

I'm guessing what's happening is described by [this](https://stackoverflow.com/a/39313448/1078529) answer, 

> The zero-argument form of super requires that the method containing it have an explicit (i.e., non-varargs) first argument

**Comment by stevengj** [comment]
My impression is that `super` internally takes [two arguments, a type and an instance](https://stackoverflow.com/questions/31232098/how-to-call-super-method), and if you call `super()` in a class method then Python automatically inserts these arguments.

**Comment by stevengj** [comment]
See also [here](http://pythonextensionpatterns.readthedocs.io/en/latest/super_call.html), which also explicitly passes `(type, self)` as the arguments.

**Comment by marius311** [comment]
> you call super() in a class method then Python automatically inserts these arguments

That's right, my point is that I think the way in which Python automatically inserts these arguments must be being broken by the way in which PyCall calls or constructs the class method. The link above states that the zero-arg call gets broken if you define only a varargs version of your class method. I.e., in pure Python the following is the same error we see above:

```python
>>> class Foo:
...     def __str__(*args):
...         super().__str__()
... 
>>> Foo().__str__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in __str__
RuntimeError: super(): no arguments
```
you need an explicit non-varargs first argument for the `super()` magic to work.
```python
>>> class Bar:
...     def __str__(self,*args):
...         super().__str__()
... 
>>> Bar().__str__()
```

My guess (and I could be wrong) is that PyCall takes my Julia definition of `__str__(self) = ...` which was written without varargs, but translates it into something that Python thinks is only varargs, and hence the `super()` magic doesn't work. 

I don't know the internals of PyCall well enough to say, could that be the case? And if so, is it possible to tweak it so `super()` works?

**Comment by stevengj** [comment]
I don't think there is any way to make this work, short of recognizing the `super` function specially in the `@pydef` macro.  Python is doing some magic when it compiles a pure-Python class, whereas the methods here are just ordinary Julia functions that happen to be packaged into a Python class.

**Comment by stevengj** [comment]
(Your Julia function isn't being "translated" into a Python function.  It is just being called from Python.  Python knows nothing about the contents of the function.)

**Comment by cstjean** [comment]
We could add `super() = pybuiltin(:super)(Bar,self)` into each method's body, in the macroexpansion.

**Comment by stevengj** [comment]
I guess that's a reasonable solution, since it will get optimized away if it isn't used.   Maybe it should be called `pysuper()`, and we could define a corresponding top-level `pysuper(T,o)` function.
