### ISSUE TITLE
py"print 'hello world'" fails in Julia 0.6

### ISSUE THREAD

**Issue by rahulkp220** [JuliaPy/PyCall.jl#434]
I am trying to run this code, but it fails throwing these errors.
```
julia> py"print 'hello world'"
ERROR: PyError (ccall(@pysym(:Py_CompileString), PyPtr, (Cstring, Cstring, Cint), sb, fname, input_type)) <type 'exceptions.SyntaxError'>
SyntaxError('invalid syntax', ('/Users/rlakhanpal/.julia/v0.6/PyCall/src/pyeval.jl', 1, 5, "print 'hello world'"))

Stacktrace:
 [1] pyerr_check at /Users/rlakhanpal/.julia/v0.6/PyCall/src/exception.jl:56 [inlined]
 [2] pyerr_check at /Users/rlakhanpal/.julia/v0.6/PyCall/src/exception.jl:61 [inlined]
 [3] macro expansion at /Users/rlakhanpal/.julia/v0.6/PyCall/src/exception.jl:81 [inlined]
 [4] pyeval_(::String, ::PyCall.PyDict{String,PyCall.PyObject,false}, ::PyCall.PyDict{String,PyCall.PyObject,false}, ::Int64, ::String) at /Users/rlakhanpal/.julia/v0.6/PyCall/src/pyeval.jl:20

```

**Comment by stevengj** [comment]
If you give `py"..."` a single-line input, then it is equivalent to the `eval` function in Python, and [eval doesn't support the print statement](https://stackoverflow.com/questions/13851389/what-are-valid-statements-inside-a-python-eval) even in Python:
```py
>>> eval("print 'hello world'")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1
    print 'hello world'
```
To evaluate `print` in Python, you have to do `exec`, and this is done by `py"""..."""` when you give it a multiline string:
```jl
julia> py"""
       print 'hello world'
       """
hello world
```

**Comment by stevengj** [comment]
I've updated the README to clarify this.

**Comment by rahulkp220** [comment]
Thank you! This works.
```
julia> py"""
       print 'hello world'
       """
hello world
```
