### ISSUE TITLE
env not activated using Conda.jl on Windows 10

### ISSUE THREAD

**Issue by alkorang** [JuliaPy/PyCall.jl#561]
I'm not sure this is the right place to open this issue, but here it goes.

```julia
(v1.0) pkg> add PyCall
 Resolving package versions...
 Installed Conda ────────── v1.0.1
 Installed VersionParsing ─ v1.1.2
 Installed MacroTools ───── v0.4.4
 Installed PyCall ───────── v1.18.4
  Updating `C:\Users\alkorang\.julia\environments\v1.0\Project.toml`
  [438e738f] + PyCall v1.18.4
  Updating `C:\Users\alkorang\.julia\environments\v1.0\Manifest.toml`
  [8f4d0f93] + Conda v1.0.1
  [1914dd2f] + MacroTools v0.4.4
  [438e738f] + PyCall v1.18.4
  [81def892] + VersionParsing v1.1.2
  Building Conda ─→ `C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\build.log`
  Building PyCall → `C:\Users\alkorang\.julia\packages\PyCall\rUul9\deps\build.log`

julia> using PyCall
[ Info: Precompiling PyCall [438e738f-606a-5dbb-bf0a-cddfbfd45ab0]

julia> py"""
       import numpy
       print(numpy.random.rand(4, 4))
       """
ERROR: PyError ($(Expr(:escape, :(ccall(#= C:\Users\alkorang\.julia\packages\PyCall\rUul9\src\pyeval.jl:23 =# @pysym(:PyEval_EvalCode), PyPtr, (PyPtr, PyPtr, PyPtr), o, globals, locals))))) <class 'ImportError'>
ImportError("\nImporting the multiarray numpy extension module failed.  Most\nlikely you are trying to import a failed build of numpy.\nIf you're working with a numpy git repo, try `git clean -xdf` (removes all\nfiles not under version control).  Otherwise reinstall numpy.\n\nOriginal error was: DLL load failed: 지정된 모듈을 찾을 수 없습니다.\n")
  File "C:\Users\alkorang\.julia\packages\PyCall\rUul9\src\pyeval.jl", line 1, in <module>
    const Py_single_input = 256  # from Python.h
  File "C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)

Stacktrace:
 [1] pyerr_check at C:\Users\alkorang\.julia\packages\PyCall\rUul9\src\exception.jl:60 [inlined]
 [2] pyerr_check at C:\Users\alkorang\.julia\packages\PyCall\rUul9\src\exception.jl:64 [inlined]
 [3] macro expansion at C:\Users\alkorang\.julia\packages\PyCall\rUul9\src\exception.jl:85 [inlined]
 [4] pyeval_(::String, ::PyDict{String,PyObject,false}, ::PyDict{String,PyObject,false}, ::Int64, ::String) at C:\Users\alkorang\.julia\packages\PyCall\rUul9\src\pyeval.jl:20
 [5] top-level scope at C:\Users\alkorang\.julia\packages\PyCall\rUul9\src\pyeval.jl:216

julia>
```
("지정된 모듈을 찾을 수 없습니다." means "The specified procedure could not be found.")

build.log:
```
Warning: 'defaults' already in 'channels' list, moving to the top
Solving environment: ...working... done

# All requested packages already installed.

Solving environment: ...working... done

icc_rt-2017.0.4      | 8.0 MB    |            |   0% 
(more status bars)
blas-1.0             | 6 KB      | ########## | 100% 
## Package Plan ##

  environment location: C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr

  added / updated specs: 
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    icc_rt-2017.0.4            |       h97af966_0         8.0 MB
    numpy-base-1.15.1          |   py37h8128ebf_0         3.9 MB
    mkl_random-1.0.1           |   py37h77b88f5_1         267 KB
    numpy-1.15.1               |   py37ha559c80_0          37 KB
    mkl_fft-1.0.4              |   py37h1e22a9b_1         120 KB
    mkl-2018.0.3               |                1       178.1 MB
    intel-openmp-2018.0.3      |                0         1.7 MB
    blas-1.0                   |              mkl           6 KB
    ------------------------------------------------------------
                                           Total:       192.0 MB

The following NEW packages will be INSTALLED:

    blas:         1.0-mkl              
    icc_rt:       2017.0.4-h97af966_0  
    intel-openmp: 2018.0.3-0           
    mkl:          2018.0.3-1           
    mkl_fft:      1.0.4-py37h1e22a9b_1 
    mkl_random:   1.0.1-py37h77b88f5_1 
    numpy:        1.15.1-py37ha559c80_0
    numpy-base:   1.15.1-py37h8128ebf_0


Downloading and Extracting Packages
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

┌ Info: Using the Python distribution in the Conda package by default.
└ To use a different Python version, set ENV["PYTHON"]="pythoncommand" and re-run Pkg.build("PyCall").
[ Info: Downloading miniconda installer ...
[ Info: Installing miniconda ...
[ Info: Running `conda config --add channels defaults --force` in root environment
[ Info: Running `conda update -y conda` in root environment
[ Info: Running `conda install -y numpy` in root environment
[ Info: PyCall is using C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\python.exe (Python 3.7.0) at C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\python.exe, libpython = C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\python37
[ Info: C:\Users\alkorang\.julia\packages\PyCall\rUul9\deps\deps.jl has been updated
[ Info: C:\Users\alkorang\.julia\packages\PyCall\rUul9\deps\PYTHON has been updated

```

On Anaconda Prompt:
```

(base) C:\Users\alkorang>conda list
# packages in environment at C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0
blas                      1.0                         mkl
ca-certificates           2018.03.07                    0
certifi                   2018.8.24                py37_1
cffi                      1.11.5           py37h74b6da3_1
chardet                   3.0.4                    py37_1
conda                     4.5.11                   py37_0
conda-env                 2.6.0                         1
console_shortcut          0.1.1                         3
cryptography              2.3.1            py37h74b6da3_0
icc_rt                    2017.0.4             h97af966_0
idna                      2.7                      py37_0
intel-openmp              2018.0.3                      0
menuinst                  1.4.14           py37hfa6e2cd_0
mkl                       2018.0.3                      1
mkl_fft                   1.0.4            py37h1e22a9b_1
mkl_random                1.0.1            py37h77b88f5_1
numpy                     1.15.1           py37ha559c80_0
numpy-base                1.15.1           py37h8128ebf_0
openssl                   1.0.2p               hfa6e2cd_0
pip                       10.0.1                   py37_0
pycosat                   0.6.3            py37hfa6e2cd_0
pycparser                 2.18                     py37_1
pyopenssl                 18.0.0                   py37_0
pysocks                   1.6.8                    py37_0
python                    3.7.0                hea74fb7_0
pywin32                   223              py37hfa6e2cd_1
requests                  2.19.1                   py37_0
ruamel_yaml               0.15.46          py37hfa6e2cd_0
setuptools                40.2.0                   py37_0
six                       1.11.0                   py37_1
urllib3                   1.23                     py37_0
vc                        14                   h0510ff6_3
vs2015_runtime            14.0.25123                    3
wheel                     0.31.1                   py37_0
win_inet_pton             1.0.1                    py37_1
wincertstore              0.2                      py37_0
yaml                      0.1.7                hc54c509_2

(base) C:\Users\alkorang>python
Python 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.version
'3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]'
>>> sys.prefix
'C:\\Users\\alkorang\\.julia\\packages\\Conda\\m7vem\\deps\\usr'
>>> import numpy
>>> print(numpy.random.rand(4, 4))
[[0.34115194 0.25977792 0.64975746 0.56639423]
 [0.78872204 0.43838955 0.94753974 0.45521152]
 [0.39978503 0.59728518 0.91029691 0.99104591]
 [0.30680109 0.30656545 0.4197914  0.3900603 ]]
>>> exit()

(base) C:\Users\alkorang>conda env list
# conda environments:
#
base                  *  C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr


(base) C:\Users\alkorang>
```

The same problem comes from when I call python.exe directly by path, it does not activate the base env.
```

C:\Users\alkorang>.julia\packages\Conda\m7vem\deps\usr\python.exe
Python 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: 지정된 모듈을 찾을 수 없습니다.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: 지정된 모듈을 찾을 수 없습니다.

>>>
```

**Comment by stevengj** [comment]
If the error appears in Python, you should file an issue with Anaconda — it has nothing to do with PyCall.

You could try to re-install `numpy` with
```jl
using Conda
rm(Conda.ROOTENV, recursive=true)
```
followed by running `build PyCall` at the pkg prompt.

**Comment by stevengj** [comment]
`unlink: operation not permitted (EPERM)` probably means that you installed some Julia packages as root or sudo, and the permissions on your `.julia` directory got messed up.

If you don't know how to fix the permissions using `chown`, I would recommend `sudo rm -rf ~/.julia` to remove your `.julia` directory and then start over.

**Comment by alkorang** [comment]
Thank you for your comments.

> unlink: operation not permitted (EPERM) probably means that you installed some Julia packages as root or sudo, and the permissions on your .julia directory got messed up

Sorry to say, Windows doesn't have root and sudo. and I installed it on my user directory without any UAC pop-up. I manually deleted the folder (of course without UAC pop-up) and reinstalled but the same error occurs.

> If you don't know how to fix the permissions using chown, I would recommend sudo rm -rf ~/.julia to remove your .julia directory and then start over (assuming you don't have any development code that you need to save in that directory!).

I tried this several times, including delete all Python installations and their configurations (env, PATH, `%USERPROFILE%\.conda`, etc.)

Again, I can import numpy through Anaconda Prompt which activate `base` env. But I cannot import numpy when I run Python binary by calling `.julia\packages\Conda\m7vem\deps\usr\python.exe`, and the same error occurs when I run the same thing with `@py_str`.

Also, when I tried `Conda.runconda(`activate base`)`, this happens:
```julia
julia> Conda.runconda(`activate base`)
[ Info: Running `conda activate base` in root environment

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If your shell is Bash or a Bourne variant, enable conda for the current user with

    $ echo ". C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr/etc/profile.d/conda.sh" >> ~/.bashrc

or, for all users, enable conda with

    $ sudo ln -s C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr/etc/profile.d/conda.sh /etc/profile.d/conda.sh

The options above will permanently enable the 'conda' command, but they do NOT
put conda's base (root) environment on PATH.  To do so, run

    $ conda activate

in your terminal, or to put the base environment on PATH permanently, run

    $ echo "conda activate" >> ~/.bashrc

Previous to conda 4.4, the recommended way to activate conda was to modify PATH in
your ~/.bashrc file.  You should manually remove the line that looks like

    export PATH="C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr/bin:$PATH"

^^^ The above line should NO LONGER be in your ~/.bashrc file! ^^^


ERROR: failed process: Process(setenv(`'C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\Scripts\conda.exe' activate base`,["USERDOMAIN_ROAMINGPROFILE=DESKTOP-UE8ORGU", "HOMEPATH=\\Users\\alkorang", "ProgramData=C:\\ProgramData", "ProgramW6432=C:\\Program Files", "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC", "SESSIONNAME=Console", "APPDATA=C:\\Users\\alkorang\\AppData\\Roaming", "PUBLIC=C:\\Users\\Public", "USERDOMAIN=DESKTOP-UE8ORGU", "OS=Windows_NT", "PROCESSOR_REVISION=3a09", "TMP=C:\\Users\\alkorang\\AppData\\Local\\Temp", "ALLUSERSPROFILE=C:\\ProgramData", "Path=C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\LLVM\\bin;C:\\Program Files\\Git\\cmd;C:\\Users\\alkorang\\.cargo\\bin;C:\\Users\\alkorang\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\Bandizip\\;C:\\Users\\alkorang\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\alkorang\\AppData\\Local\\Julia-1.0.0\\bin;C:\\Users\\alkorang\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\alkorang\\AppData\\Local\\atom\\bin;", "COMPUTERNAME=DESKTOP-UE8ORGU", "USERNAME=alkorang", "CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files", "CommonProgramFiles=C:\\Program Files\\Common Files", "CONDARC=C:\\Users\\alkorang\\.julia\\packages\\Conda\\m7vem\\deps\\usr\\condarc-julia.yml", "USERPROFILE=C:\\Users\\alkorang", "PSModulePath=C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules", "PROCESSOR_LEVEL=6", "TEMP=C:\\Users\\alkorang\\AppData\\Local\\Temp", "SystemDrive=C:", "HOMEDRIVE=C:", "PYTHONIOENCODING=UTF-8", "LOCALAPPDATA=C:\\Users\\alkorang\\AppData\\Local", "PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 58 Stepping 9, GenuineIntel", "DriverData=C:\\Windows\\System32\\Drivers\\DriverData", "NUMBER_OF_PROCESSORS=8", "=::=::\\", "ComSpec=C:\\WINDOWS\\system32\\cmd.exe", "SystemRoot=C:\\WINDOWS", "OneDrive=C:\\Users\\alkorang\\OneDrive", "VBOX_MSI_INSTALL_PATH=C:\\Program Files\\Oracle\\VirtualBox\\", "ProgramFiles(x86)=C:\\Program Files (x86)", "LOGONSERVER=\\\\DESKTOP-UE8ORGU", "CONDA_PREFIX=C:\\Users\\alkorang\\.julia\\packages\\Conda\\m7vem\\deps\\usr", "windir=C:\\WINDOWS", "CommonProgramW6432=C:\\Program Files\\Common Files", "ProgramFiles=C:\\Program Files", "PROCESSOR_ARCHITECTURE=AMD64", "OPENBLAS_MAIN_FREE=1"]), ProcessExited(1)) [1]
Stacktrace:
 [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at .\error.jl:42
 [2] pipeline_error at .\process.jl:695 [inlined]
 [3] #run#505(::Bool, ::Function, ::Cmd) at .\process.jl:653
 [4] run at .\process.jl:651 [inlined]
 [5] macro expansion at .\logging.jl:307 [inlined]
 [6] runconda(::Cmd, ::String) at C:\Users\alkorang\.julia\packages\Conda\m7vem\src\Conda.jl:112
 [7] runconda(::Cmd) at C:\Users\alkorang\.julia\packages\Conda\m7vem\src\Conda.jl:111
 [8] top-level scope at none:0

julia>
```

Anaconda Prompt activate `base` env by running this:
`%windir%\System32\cmd.exe "/K" C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\Scripts\activate.bat C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr`

I'm still finding the answer. Anyway, it is clear that the issue does not come from PyCall. I'll continue this in Conda.jl or Anaconda.
