### ISSUE TITLE
"symbol EVP_idea_cbc version OPENSSL_1_1_0 not defined"

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaPy/PyCall.jl#787]
I got down to MWE (only happens with correct password):

```
$ julia --startup-file=no
 _/ |\__'_|_|_|\__'_|  |  Commit 4e2fb5c72c (6 days old master)

julia> using Pandas

julia> using PyCall

julia> using Plots


julia> 

julia> py"""
       from symmetry.carbon.carbon_client import CarbonClient
       from symmetry.carbon.conf.carbon_config import CarbonEnv

       client = CarbonClient(CarbonEnv.prd, auth_params={'user_name': 'ressvc_sym', 'password': 'CENSORED'})
       """
julia: relocation error: /home/pharaldsson_sym/.julia/artifacts/e6e5f41352118bbeb44677765ebccab8c151c72a/lib/libssl.so: symbol EVP_idea_cbc version OPENSSL_1_1_0 not defined in file libcrypto.so.1.1 with link time reference
```

The strange thing is, while this fails now repeatedly, it worked before and I could get data from the client into a dataframe.

The error seems to me about the client machine config, but could it be people at work changing server config around midnight?

Also strange that I never get this error in Python directly (while see on hang):

```
$ python3
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from symmetry.carbon.carbon_client import CarbonClient
>>> from symmetry.carbon.conf.carbon_config import CarbonEnv
>>> client = CarbonClient(CarbonEnv.prd, auth_params={'user_name': 'ressvc_sym', 'password': 'CENSORED'})
>>> 
>>> 
>>> client
<symmetry.carbon.carbon_client.CarbonClient object at 0x7f0a72035470>
>>> 
>>> client
<symmetry.carbon.carbon_client.CarbonClient object at 0x7f0a72035470>
>>> 
```

but note that when I try to exit, with CTRL-D, it hangs.

https://stackoverflow.com/questions/23016514/how-do-i-enable-evp-functions-in-openssl

**Comment by PallHaraldsson** [comment]
No hang (on exit) with Python or Julia on intentionally incorrect password:

```
>>> client = CarbonClient(CarbonEnv.prd, auth_params={'user_name': 'ressvc_sym', 'password': 'INVALID'})
WARNING:symmetry.carbon.auth.auth_client:Invalid token response {'Status': 'unknown', 'Token': ''}
WARNING:symmetry.carbon.auth.auth_client:First auth response failed waiting for all responses...
WARNING:symmetry.carbon.auth.auth_client:Invalid token response {'Status': 'unknown', 'Token': ''}
WARNING:symmetry.carbon.carbon_client:Error connecting to auth service: 'set' object has no attribute 'result'
[HERE a long pause, maybe intentional.]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pharaldsson_sym/.local/lib/python3.6/site-packages/symmetry/carbon/carbon_client.py", line 128, in __init__
    timeout)
  File "/home/pharaldsson_sym/.local/lib/python3.6/site-packages/symmetry/carbon/conf/carbon_config.py", line 100, in load_config_from_db
    client = CarbonMongoClient(config_db, env == CarbonEnv.prd)
  File "/home/pharaldsson_sym/.local/lib/python3.6/site-packages/symmetry/carbon/db/mongo/mongo_adapter.py", line 31, in __init__
    auth_db.authenticate(config['user'], pwd, mechanism=mechanism)
  File "/home/pharaldsson_sym/.local/lib/python3.6/site-packages/pymongo/database.py", line 1471, in authenticate
    connect=True)
  File "/home/pharaldsson_sym/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 750, in _cache_credentials
    writable_preferred_server_selector)
  File "/home/pharaldsson_sym/.local/lib/python3.6/site-packages/pymongo/topology.py", line 235, in select_server
    address))
  File "/home/pharaldsson_sym/.local/lib/python3.6/site-packages/pymongo/topology.py", line 193, in select_servers
    selector, server_timeout, address)
  File "/home/pharaldsson_sym/.local/lib/python3.6/site-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: symmdb01b:27000: [Errno -2] Name or service not known,symmdb01k:27000: [Errno -2] Name or service not known,symmdb01e:27000: [Errno -2] Name or service not known
```

and:

```
 julia --startup-file=no -q
julia> using PyCall

julia> py"""
       from symmetry.carbon.carbon_client import CarbonClient
       from symmetry.carbon.conf.carbon_config import CarbonEnv
       """

julia> py"""
       client = CarbonClient(CarbonEnv.prd, auth_params={'user_name': 'ressvc_sym', 'password': 'INVALID'})
       """
WARNING:symmetry.carbon.auth.auth_client:Invalid token response {'Status': 'unknown', 'Token': ''}
WARNING:symmetry.carbon.auth.auth_client:First auth response failed waiting for all responses...
WARNING:symmetry.carbon.auth.auth_client:Invalid token response {'Status': 'unknown', 'Token': ''}
WARNING:symmetry.carbon.carbon_client:Error connecting to auth service: 'set' object has no attribute 'result'

ERROR: PyError ($(Expr(:escape, :(ccall(#= /home/pharaldsson_sym/.julia/packages/PyCall/zqDXB/src/pyeval.jl:38 =# @pysym(:PyEval_EvalCode), PyPtr, (PyPtr, PyPtr, PyPtr), o, globals, locals))))) <class 'pymongo.errors.ServerSelectionTimeoutError'>
ServerSelectionTimeoutError('symmdb01e:27000: [Errno -2] Name or service not known,symmdb01b:27000: [Errno -2] Name or service not known,symmdb01k:27000: [Errno -2] Name or service not known',)
  File "/home/pharaldsson_sym/.julia/packages/PyCall/zqDXB/src/pyeval.jl", line 1, in <module>
    const Py_single_input = 256  # from Python.h
  File "/home/pharaldsson_sym/.local/lib/python3.6/site-packages/symmetry/carbon/carbon_client.py", line 128, in __init__
    timeout)
  File "/home/pharaldsson_sym/.local/lib/python3.6/site-packages/symmetry/carbon/conf/carbon_config.py", line 100, in load_config_from_db
    client = CarbonMongoClient(config_db, env == CarbonEnv.prd)
  File "/home/pharaldsson_sym/.local/lib/python3.6/site-packages/symmetry/carbon/db/mongo/mongo_adapter.py", line 31, in __init__
    auth_db.authenticate(config['user'], pwd, mechanism=mechanism)
  File "/home/pharaldsson_sym/.local/lib/python3.6/site-packages/pymongo/database.py", line 147
```
