### ISSUE TITLE
Exception when trying to navigate Main.PyCall module

### ISSUE THREAD

**Issue by paulmelis** [JuliaPy/PyCall.jl#813]
I was trying to explore what Python functions are available in the `Main.PyCall` module, but apparently that isn't possible? Or is this a bug?

```
melis@juggle 14:32:~$ python
Python 3.8.5 (default, Jul 27 2020, 08:42:51) 
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import julia
>>> from julia.api import Julia
>>> j=Julia()
>>> from julia import Main
>>> dir(Main)
['Base', 'Core', 'PyCall', '__doc__', '__loader__', '__name__', '__package__', '__spec__', '_julia']
>>> Main.PyCall
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/melis/.local/lib/python3.8/site-packages/julia/core.py", line 176, in __getattr__
    return self.__try_getattr(name)
  File "/home/melis/.local/lib/python3.8/site-packages/julia/core.py", line 191, in __try_getattr
    if self._julia.isdefined(realname):
  File "/home/melis/.local/lib/python3.8/site-packages/julia/core.py", line 645, in isdefined
    raise ValueError(
ValueError: `julia.isdefined(name)` requires at least one dot in `name`.

>>> julia.Julia
<class 'julia.core.LegacyJulia'>
>>> julia.Main
<module 'julia.Main' (<julia.core.JuliaModuleLoader object at 0x7f0083714cd0>)>

>>> julia.Main.PyCall
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/melis/.local/lib/python3.8/site-packages/julia/core.py", line 176, in __getattr__
    return self.__try_getattr(name)
  File "/home/melis/.local/lib/python3.8/site-packages/julia/core.py", line 191, in __try_getattr
    if self._julia.isdefined(realname):
  File "/home/melis/.local/lib/python3.8/site-packages/julia/core.py", line 645, in isdefined
    raise ValueError(
ValueError: `julia.isdefined(name)` requires at least one dot in `name`.

```

**Comment by stevengj** [comment]
This looks like a problem with pyjulia, not PyCall, so you should file an issue there: https://github.com/JuliaPy/pyjulia

**Comment by paulmelis** [comment]
Sorry, you're right, reported as https://github.com/JuliaPy/pyjulia/issues/414
